// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3VHe8IqMCYUxV5x3V2KLjMgO2FXDG8W4',
    appId: '1:739876449170:web:46b27e31d7406a62ffaf4b',
    messagingSenderId: '739876449170',
    projectId: 'cs3fyp-a0057',
    authDomain: 'cs3fyp-a0057.firebaseapp.com',
    storageBucket: 'cs3fyp-a0057.firebasestorage.app',
    measurementId: 'G-49RV889S42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwke1NEpDsGGMy-Pjwpcj8CfT2sa1LWXs',
    appId: '1:739876449170:android:14ba0b957f32ff97ffaf4b',
    messagingSenderId: '739876449170',
    projectId: 'cs3fyp-a0057',
    storageBucket: 'cs3fyp-a0057.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfeDPD9R7Cp5GGHD2V0ckD8PTgO458nEM',
    appId: '1:739876449170:ios:23c26bb7f7aa2d05ffaf4b',
    messagingSenderId: '739876449170',
    projectId: 'cs3fyp-a0057',
    storageBucket: 'cs3fyp-a0057.firebasestorage.app',
    iosBundleId: 'com.example.flutterTesting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfeDPD9R7Cp5GGHD2V0ckD8PTgO458nEM',
    appId: '1:739876449170:ios:23c26bb7f7aa2d05ffaf4b',
    messagingSenderId: '739876449170',
    projectId: 'cs3fyp-a0057',
    storageBucket: 'cs3fyp-a0057.firebasestorage.app',
    iosBundleId: 'com.example.flutterTesting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3VHe8IqMCYUxV5x3V2KLjMgO2FXDG8W4',
    appId: '1:739876449170:web:869316b74e523fb5ffaf4b',
    messagingSenderId: '739876449170',
    projectId: 'cs3fyp-a0057',
    authDomain: 'cs3fyp-a0057.firebaseapp.com',
    storageBucket: 'cs3fyp-a0057.firebasestorage.app',
    measurementId: 'G-XHJW9L2XTS',
  );
}
